-- REAL SQL

CREATE TABLE [dbo].[ct_EI Outcomes & Session Notes_Session Note] (
    [__forminstanceguid] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    [__ownerobjectguid] UNIQUEIDENTIFIER NULL,
    [__ownerobjecttable] VARCHAR(100) NULL,
    [__isdeleted] BIT NOT NULL DEFAULT 0,
    [__createdby] VARCHAR(100) NULL,
    [__createddate] DATETIME NULL,
    [__modifiedby] VARCHAR(100) NULL,
    [__modifieddate] DATETIME NULL,
    [txtaDebug] undefined NULL,
    [chkShowTimeSheetIssuePnl] undefined NULL,
    [chkShowDeletedApptIssuePnl] undefined NULL,
    [chkShowEmailPanel] undefined NULL,
    [txtEmailSubject] undefined NULL,
    [txtaEmailBody] undefined NULL,
    [chkSendEmail] undefined NULL,
    [txtaEmailError] undefined NULL,
    [chkShowUnlockPnl] undefined NULL,
    [chkInitialUnlock] undefined NULL,
    [chkUnlocking] undefined NULL,
    [chkShowAppointmentDetailsPnl] undefined NULL,
    [chkPreviousNoteError] undefined NULL,
    [txtaShowCreateError] undefined NULL,
    [chkShowMakeUpPnl] undefined NULL,
    [chkShowSessionTypePnl] undefined NULL,
    [chkShowOutcomesPnl] undefined NULL,
    [txtaOutcomeError] undefined NULL,
    [chkShowFamilyUpdatePnl] undefined NULL,
    [chkShowProgressNotePnl] undefined NULL,
    [chkShowCoachingStrategiesPnl] undefined NULL,
    [chkShowTargetsPnl] undefined NULL,
    [chkShowFamilyPlanPnl] undefined NULL,
    [chkShowNextSessionPnl] undefined NULL,
    [chkShowSCPnl] undefined NULL,
    [chkShowUploadPnl] undefined NULL,
    [chkShowTherapistSignaturePnl] undefined NULL,
    [txtTherapistSignatureLbl] undefined NULL,
    [txtaSignOffError] undefined NULL,
    [txtDebugMsg] undefined NULL,
    [chkShowCaregiverSignaturePnl] undefined NULL
);
GO